var BaseReporter;

BaseReporter = (function() {
  function BaseReporter(runner, options) {
    this.runner = runner;
    this.options = options;
    expect(this.runner).to.be.an('object');
    expect(this.options).to.be.an('object');
    this.stats = {
      total: this.runner.total,
      suites: 0,
      tests: 0,
      passes: 0,
      pending: 0,
      failures: 0
    };
    this.failures = [];
    this.runner.stats = this.stats;
    this.runner.on('start', (function(_this) {
      return function() {
        return _this.stats.start = new Date;
      };
    })(this));
    this.runner.on('suite', (function(_this) {
      return function(suite) {
        if (!suite.root) {
          return _this.stats.suites++;
        }
      };
    })(this));
    this.runner.on('test end', (function(_this) {
      return function(test) {
        return _this.stats.tests++;
      };
    })(this));
    this.runner.on('pass', (function(_this) {
      return function(test) {
        var medium;
        medium = test.slow() / 2;
        if (test.duration > test.slow()) {
          test.speed = 'slow';
        } else if (test.duration > medium) {
          test.speed = 'medium';
        } else {
          test.speed = 'fast';
        }
        return _this.stats.passes++;
      };
    })(this));
    this.runner.on('fail', (function(_this) {
      return function(test, err) {
        _this.stats.failures++;
        test.err = err;
        return _this.failures.push(test);
      };
    })(this));
    this.runner.on('end', (function(_this) {
      return function() {
        _this.stats.end = new Date;
        return _this.stats.duration = _this.stats.end - _this.stats.start;
      };
    })(this));
    this.runner.on('pending', (function(_this) {
      return function() {
        return _this.stats.pending++;
      };
    })(this));
  }

  return BaseReporter;

})();

module.exports = BaseReporter;

// ---
// generated by coffee-script 1.9.2
