var ClientServerBaseReporter, MochaRunner;

MochaRunner = require("../lib/MochaRunner");

ClientServerBaseReporter = (function() {
  function ClientServerBaseReporter(clientRunner, serverRunner, options) {
    this.clientRunner = clientRunner;
    this.serverRunner = serverRunner;
    this.options = options;
    expect(this.clientRunner).to.be.an('object');
    expect(this.serverRunner).to.be.an('object');
    expect(this.options).to.be.an('object');
    this.clientStats = {
      total: this.clientRunner.total,
      suites: 0,
      tests: 0,
      passes: 0,
      pending: 0,
      failures: 0
    };
    this.serverStats = {
      total: this.serverRunner.total,
      suites: 0,
      tests: 0,
      passes: 0,
      pending: 0,
      failures: 0
    };
    this.stats = {
      total: this.serverRunner.total + this.clientRunner.total,
      suites: 0,
      tests: 0,
      passes: 0,
      pending: 0,
      failures: 0
    };
    this.failures = [];
    this.clientRunner.stats = this.clientStats;
    this.serverRunner.stats = this.serverStats;
    this.registerRunnerEvents("server");
    this.registerRunnerEvents("client");
    MochaRunner.on("end all", (function(_this) {
      return function() {
        window.TEST_STATUS = {
          FAILURES: _this.stats.failures,
          DONE: true
        };
        window.DONE = true;
        return window.FAILURES = _this.stats.failures;
      };
    })(this));
  }

  ClientServerBaseReporter.prototype.registerRunnerEvents = function(where) {
    this[where + "Runner"].on('start', (function(_this) {
      return function() {
        var base, start;
        start = new Date();
        _this[where + "Stats"].start = start;
        if ((base = _this.stats).start == null) {
          base.start = start;
        }

        /*
          The total and other stats of the server runner are sent with the 'start' event,
          so we need to update the total of the stats.
          Also when running in 'serial' mode (server test first and then client tests),
          clientRunner.total is undefined because client starts running after server tests end.
         */
        _this.clientStats.total = _this.clientRunner.total;
        _this.serverStats.total = _this.serverRunner.total;
        return _this.stats.total = _this.clientStats.total + _this.serverStats.total;
      };
    })(this));
    this[where + "Runner"].on('suite', (function(_this) {
      return function(suite) {
        if (!suite.root) {
          _this.stats.suites++;
          return _this[where + "Stats"].suites++;
        }
      };
    })(this));
    this[where + "Runner"].on('test end', (function(_this) {
      return function(test) {
        return _this.stats.tests++;
      };
    })(this));
    this[where + "Runner"].on('pass', (function(_this) {
      return function(test) {
        var medium;
        medium = test.slow() / 2;
        if (test.duration > test.slow()) {
          test.speed = 'slow';
        } else if (test.duration > medium) {
          test.speed = 'medium';
        } else {
          test.speed = 'fast';
        }
        _this[where + "Stats"].passes++;
        return _this.stats.passes++;
      };
    })(this));
    this[where + "Runner"].on('fail', (function(_this) {
      return function(test, err) {
        if (test.err == null) {
          test.err = err;
        }
        _this.failures.push(test);
        _this.stats.failures++;
        return _this[where + "Stats"].failures++;
      };
    })(this));
    this[where + "Runner"].on('end', (function(_this) {
      return function() {
        var end;
        end = new Date();
        _this.stats.end = end;
        _this[where + "Stats"].end = end;
        _this.stats.duration = _this.stats.end - _this.stats.start;
        return _this[where + "Stats"].duration = _this[where + "Stats"].end - _this[where + "Stats"].start;
      };
    })(this));
    return this[where + "Runner"].on('pending', (function(_this) {
      return function() {
        _this.stats.pending++;
        return _this[where + "Stats"].pending++;
      };
    })(this));
  };

  return ClientServerBaseReporter;

})();

module.exports = ClientServerBaseReporter;

// ---
// generated by coffee-script 1.9.2
